// ============================================================================
// ITEMS-DATA.JS — общая база предметов (лут, ингредиенты, украшения и т.д.)
// Подключается и на index.html (на будущее — для игроков), и на gm.html
// (панель «База предметов»), чтобы обе страницы видели одни и те же данные.
// ============================================================================

const allItems = [
    // --- Ювелирные изделия ---
    { name: "Серебряное кольцо", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 30 },
    { name: "Серебряное кольцо с аметистом", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 180 },
    { name: "Серебряное кольцо с гранатом", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 160 },
    { name: "Серебряное кольцо с рубином", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 260 },
    { name: "Золотое кольцо", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 75 },
    { name: "Золотое кольцо с бриллиантом", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 900 },
    { name: "Золотое кольцо с изумрудом", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 700 },
    { name: "Золотое кольцо с сапфиром", category: "Ювелирные изделия", type: "jewelry", slot: "ring", weight: 0.25, price: 500 },
    // Обручи
    { name: "Медный обруч с ониксом", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 50 },
    { name: "Медный обруч с лунным камнем", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 100 },
    { name: "Медный обруч с рубином", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 150 },
    { name: "Медный обруч с сапфиром", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 200 },
    { name: "Серебряный обруч с лунным камнем", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 250 },
    { name: "Нефритовый обруч с сапфиром", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 300 },
    { name: "Нефритовый обруч с изумрудом", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 350 },
    { name: "Серебряный обруч с сапфиром", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 400 },
    { name: "Золотой обруч с рубином", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 450 },
    { name: "Золотой обруч с изумрудом", category: "Ювелирные изделия", type: "jewelry", slot: "circlet", weight: 2, price: 500 },
    // Ожерелья
    { name: "Серебряное ожерелье", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 60 },
    { name: "Серебряное ожерелье с изумрудом", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 830 },
    { name: "Серебряное ожерелье с гранатами", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 380 },
    { name: "Серебряное ожерелье с сапфиром", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 580 },
    { name: "Золотое ожерелье", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 120 },
    { name: "Золотое ожерелье с бриллиантом", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 1200 },
    { name: "Золотое ожерелье с рубином", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 550 },
    { name: "Золотое ожерелье с аметистами", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 485 },
    { name: "Амулет (Аэдра)", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 1, price: 100 },
    { name: "Кулон Восточной имперской компании", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 0.5, price: 25 },
    { name: "Амулет скаала", category: "Ювелирные изделия", type: "jewelry", slot: "necklace", weight: 1, price: 1000 },

    // --- 2. Ингредиенты для кузнечного дела ---
    { name: "Кожа", category: "Кузнечные ингредиенты", type: "misc", weight: 2, price: 10 },
    { name: "Полоски кожи", category: "Кузнечные ингредиенты", type: "misc", weight: 0.1, price: 3 },
    { name: "Железный слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 7 },
    { name: "Стальной слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 29 },
    { name: "Корундовый слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 40 },
    { name: "Двемерский слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 30 },
    { name: "Орихалковый слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 45 },
    { name: "Ртутный слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 60 },
    { name: "Лунный камень", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 75 },
    { name: "Малахитовый слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 100 },
    { name: "Эбонитовый слиток", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 150 },
    { name: "Железная руда", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 2 },
    { name: "Корундовая руда", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 20 },
    { name: "Эбонитовая руда", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 60 },
    { name: "Золотая руда", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 50 },
    { name: "Малахитовая руда", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 20 },
    { name: "Орихалковая руда", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 20 },
    { name: "Ртутная руда", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 25 },
    { name: "Сталгрим", category: "Кузнечные ингредиенты", type: "misc", weight: 1, price: 70 },

    // --- 3. Шкуры ---
    { name: "Шкура медведя", category: "Шкуры", type: "misc", weight: 3, price: 50 },
    { name: "Шкура пещерного медведя", category: "Шкуры", type: "misc", weight: 3, price: 60 },
    { name: "Шкура белого медведя", category: "Шкуры", type: "misc", weight: 3, price: 75 },
    { name: "Шкура саблезуба", category: "Шкуры", type: "misc", weight: 2, price: 25 },
    { name: "Шкура снежного саблезуба", category: "Шкуры", type: "misc", weight: 2, price: 40 },
    { name: "Волчья шкура", category: "Шкуры", type: "misc", weight: 1, price: 10 },
    { name: "Шкура снежного волка", category: "Шкуры", type: "misc", weight: 1, price: 15 },
    { name: "Козья шкура", category: "Шкуры", type: "misc", weight: 1, price: 5 },
    { name: "Коровья шкура", category: "Шкуры", type: "misc", weight: 2, price: 10 },
    { name: "Оленья шкура", category: "Шкуры", type: "misc", weight: 2, price: 10 },
    { name: "Лошадиная шкура", category: "Шкуры", type: "misc", weight: 2, price: 15 },
    { name: "Шкура лисицы", category: "Шкуры", type: "misc", weight: 0.5, price: 5 },
    { name: "Шкура снежной лисицы", category: "Шкуры", type: "misc", weight: 0.5, price: 7 },

    // --- 4. Камни душ и драгоценности ---
    { name: "Крохотный камень душ", category: "Камни душ", type: "misc", weight: 0.1, price: 10 },
    { name: "Маленький камень душ", category: "Камни душ", type: "misc", weight: 0.2, price: 25 },
    { name: "Обычный камень душ", category: "Камни душ", type: "misc", weight: 0.333, price: 50 },
    { name: "Большой камень душ", category: "Камни душ", type: "misc", weight: 0.5, price: 100 },
    { name: "Великий камень душ", category: "Камни душ", type: "misc", weight: 0.5, price: 200 },
    { name: "Чёрный камень душ", category: "Камни душ", type: "misc", weight: 1, price: 300 },
    { name: "Аметист", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 120 },
    { name: "Бриллиант", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 800 },
    { name: "Гранат", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 100 },
    { name: "Изумруд", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 600 },
    { name: "Рубин", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 200 },
    { name: "Сапфир", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 400 },
    { name: "Безупречный аметист", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 180 },
    { name: "Безупречный бриллиант", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 1000 },
    { name: "Безупречный гранат", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 150 },
    { name: "Безупречный изумруд", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 750 },
    { name: "Безупречный рубин", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 350 },
    { name: "Безупречный сапфир", category: "Драгоценные камни", type: "misc", weight: 0.1, price: 500 },

    // --- 5. Походное снаряжение ---
    { name: "Спальный мешок", category: "Походное снаряжение", type: "misc", weight: 3, price: 75 },
    { name: "Палатка (15x15 футов)", category: "Походное снаряжение", type: "misc", weight: 10, price: 300 },
    { name: "Алхимический куб", category: "Походное снаряжение", type: "misc", weight: 5, price: 450 },
    { name: "Подсумок на 2 зелья", category: "Походное снаряжение", type: "misc", weight: 2, price: 50 },
    { name: "Подсумок на 4 зелья", category: "Походное снаряжение", type: "misc", weight: 2, price: 250 },
    { name: "Подсумок на 6 зелий", category: "Походное снаряжение", type: "misc", weight: 2, price: 400 },
    { name: "Подсумок на 8 зелий", category: "Походное снаряжение", type: "misc", weight: 2, price: 800 },
    { name: "Карта владения", category: "Походное снаряжение", type: "misc", weight: 1, price: 150 },
    { name: "Котелок с столовыми приборами", category: "Походное снаряжение", type: "misc", weight: 10, price: 75 },
    { name: "Набор для костра", category: "Походное снаряжение", type: "misc", weight: 5, price: 25 },
    { name: "Походный рюкзак", category: "Походное снаряжение", type: "misc", weight: 5, price: 250 },
    { name: "Факел", category: "Походное снаряжение", type: "misc", weight: 1, price: 10 },
    { name: "Полено", category: "Походное снаряжение", type: "misc", weight: 5, price: 5 },
    { name: "Лечебная припарка", category: "Походное снаряжение", type: "misc", weight: 0.5, price: 40 },

    // --- 6. Двемерские детали ---
    { name: "Сердечник генератора центуриона", category: "Двемерские детали", type: "misc", weight: 4, price: 131 },
    { name: "Малый двемерский рычаг", category: "Двемерские детали", type: "misc", weight: 2, price: 15 },
    { name: "Малая двемерская металлическая пластина", category: "Двемерские детали", type: "misc", weight: 2, price: 15 },
    { name: "Двемерский рычаг", category: "Двемерские детали", type: "misc", weight: 2, price: 15 },
    { name: "Двемерский металлолом", category: "Двемерские детали", type: "misc", weight: 2, price: 15 },
    { name: "Двемерский гироскоп", category: "Двемерские детали", type: "misc", weight: 2, price: 15 },
    { name: "Двемерская шестерня", category: "Двемерские детали", type: "misc", weight: 10, price: 5 },
    { name: "Двемерская металлическая отливка", category: "Двемерские детали", type: "misc", weight: 25, price: 25 },
    { name: "Гнутый двемерский металлолом", category: "Двемерские детали", type: "misc", weight: 3, price: 15 },
    { name: "Большая декоративная двемерская балка", category: "Двемерские детали", type: "misc", weight: 15, price: 10 },
    { name: "Большая двемерская металлическая пластина", category: "Двемерские детали", type: "misc", weight: 3, price: 15 },
    { name: "Большая двемерская балка", category: "Двемерские детали", type: "misc", weight: 20, price: 15 },

    // --- 7. Бытовые предметы ---
    { name: "Метла", category: "Бытовые предметы", type: "misc", weight: 1, price: 1 },
    { name: "Бадья", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 1 },
    { name: "Вилка", category: "Бытовые предметы", type: "misc", weight: 1, price: 1 },
    { name: "Деревянная миска", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 1 },
    { name: "Бивень мамонта", category: "Бытовые предметы", type: "misc", weight: 5, price: 150 },
    { name: "Инструмент для бальзамирования", category: "Бытовые предметы", type: "misc", weight: 1, price: 2 },
    { name: "Испорченная книга", category: "Бытовые предметы", type: "misc", weight: 1, price: 1 },
    { name: "Казан", category: "Бытовые предметы", type: "misc", weight: 2, price: 4 },
    { name: "Корзина", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 1 },
    { name: "Кран", category: "Бытовые предметы", type: "misc", weight: 2, price: 1 },
    { name: "Кубок", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 5 },
    { name: "Пивная кружка", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 1 },
    { name: "Чугунный ковш", category: "Бытовые предметы", type: "misc", weight: 3, price: 2 },
    { name: "Чугунная кастрюля", category: "Бытовые предметы", type: "misc", weight: 4, price: 2 },
    { name: "Чашка", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 5 },
    { name: "Утюг", category: "Бытовые предметы", type: "misc", weight: 1, price: 5 },
    { name: "Уголь", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 2 },
    { name: "Ящик вина", category: "Бытовые предметы", type: "misc", weight: 6, price: 2 },
    { name: "Клык хоркера", category: "Бытовые предметы", type: "misc", weight: 1, price: 15 },
    { name: "Череп троля", category: "Бытовые предметы", type: "misc", weight: 3, price: 5 },
    { name: "Деревянный меч", category: "Бытовые предметы", type: "misc", weight: 2, price: 25 },
    { name: "Зелёное/красное платье для девочки", category: "Бытовые предметы", type: "misc", weight: 1, price: 25 },
    { name: "Соль", category: "Бытовые предметы", type: "misc", weight: 0.2, price: 2 },
    { name: "Мешок муки", category: "Бытовые предметы", type: "misc", weight: 0.5, price: 1 },
    { name: "Масло", category: "Бытовые предметы", type: "misc", weight: 0.2, price: 2 },
    { name: "Тарелка", category: "Бытовые предметы", type: "misc", weight: 0.2, price: 1 },
    { name: "Пачка сигарет (10 шт, восстанавливает 5 маны)", category: "Бытовые предметы", type: "misc", weight: 1, price: 50 },
    { name: "Трубка для курения", category: "Бытовые предметы", type: "misc", weight: 0.1, price: 5 },
    { name: "Мешочек Вазьмицы (хватает на 10 раз)", category: "Бытовые предметы", type: "misc", weight: 0.1, price: 10 },
    { name: "Пергамент", category: "Бытовые предметы", type: "misc", weight: 0.1, price: 5 },
    { name: "Чернила", category: "Бытовые предметы", type: "misc", weight: 0.1, price: 15 },
    { name: "Лопата", category: "Бытовые предметы", type: "misc", weight: 4, price: 3 },
    { name: "Серебряный кувшин", category: "Бытовые предметы", type: "misc", weight: 2, price: 30 },
    { name: "Серебряный кубок", category: "Бытовые предметы", type: "misc", weight: 1, price: 15 },
    { name: "Кукла", category: "Бытовые предметы", type: "misc", weight: 2, price: 10 },
    { name: "Древняя нордская кирка", category: "Бытовые предметы", type: "misc", weight: 5, price: 100 },

    // --- 8. Ингредиенты для алхимии (полный список) ---
    { name: "Абесинский окунь", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 15 },
    { name: "Алый корень Нирна", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 10 },
    { name: "Белянка", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 2 },
    { name: "Бесовский гриб", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 2 },
    { name: "Бойцовая рыбка", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 15 },
    { name: "Болотный стручок", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 5 },
    { name: "Большие рога", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 4 },
    { name: "Бородатый мох", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 2 },
    { name: "Вересковое сердце", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 20 },
    { name: "Ветка чертополоха", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Виноград джазби", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 2 },
    { name: "Гигантский лишайник", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 5 },
    { name: "Глаз саблезуба", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Гниль Намиры", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 2 },
    { name: "Голубой горноцвет", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Двемерское масло", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 15 },
    { name: "Жареная злокрысья кожа", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 2 },
    { name: "Жемчужина", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Живица сприггана", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 15 },
    { name: "Жир тролля", category: "Ингредиенты для алхимии", type: "misc", weight: 1, price: 15 },
    { name: "Зубы ледяного привидения", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 30 },
    { name: "Икра рыбы-убийцы", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 3 },
    { name: "Корень Нирна", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 10 },
    { name: "Красный горноцвет", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Клешня грязевого краба", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 2 },
    { name: "Клык саблезуба", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 2 },
    { name: "Клюв ястреба", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 15 },
    { name: "Коготь ворожеи", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 20 },
    { name: "Костная мука", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 5 },
    { name: "Кровавый венец", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 10 },
    { name: "Крыло лунного мотылька", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 5 },
    { name: "Крыло монарха", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 3 },
    { name: "Крыло синей бабочки", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Куриное яйцо", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 2 },
    { name: "Лаванда", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Лиловый горноцвет", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Лунный сахар", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 50 },
    { name: "Лютый гриб", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 12 },
    { name: "Маленькая жемчужина", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Маленькие рога", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Медвежьи когти", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Медовые соты", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 5 },
    { name: "Мора тапинелла", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 4 },
    { name: "Морозная мириам", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Морозная соль", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 100 },
    { name: "Морской жёлудь", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 5 },
    { name: "Мухомор", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Огненная соль", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 50 },
    { name: "Оранжевая стрекоза", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Палец великана", category: "Ингредиенты для алхимии", type: "misc", weight: 1, price: 20 },
    { name: "Паслён", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 8 },
    { name: "Паучье яйцо", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 5 },
    { name: "Пелена дымка", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Перья ворожеи", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 20 },
    { name: "Перья ястреба", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 15 },
    { name: "Ползучая лоза", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 1 },
    { name: "Прах вампира", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 25 },
    { name: "Пушица", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Пчела", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 3 },
    { name: "Пчелиное гнездо", category: "Ингредиенты для алхимии", type: "misc", weight: 1, price: 5 },
    { name: "Пшеница", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 5 },
    { name: "Светящаяся пыль", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 20 },
    { name: "Светящийся гриб", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 5 },
    { name: "Сердце даэдра", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 250 },
    { name: "Серебристый окунь", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 15 },
    { name: "Синяя стрекоза", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Сиродильский лопатохвост", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 15 },
    { name: "Снежные ягоды", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 4 },
    { name: "Собачий корень", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 5 },
    { name: "Соль", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 2 },
    { name: "Соль пустоты", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 125 },
    { name: "Стержневой корень", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 15 },
    { name: "Толчёный бивень мамонта", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 2 },
    { name: "Торакс светлячка", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Травяной стручок", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Ухо фалмера", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 10 },
    { name: "Хвост злокрыса", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 3 },
    { name: "Хисткарп", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 6 },
    { name: "Чеснок", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 1 },
    { name: "Человеческое сердце", category: "Ингредиенты для алхимии", type: "misc", weight: 1, price: 0 },
    { name: "Человечье мясо", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 1 },
    { name: "Чешуйчатка", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 4 },
    { name: "Чешуя рыбы-убийцы", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 3 },
    { name: "Эктоплазма", category: "Ингредиенты для алхимии", type: "misc", weight: 0.333, price: 25 },
    { name: "Эльфийское ухо", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 10 },
    { name: "Ягоды можжевельника", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Ядовитый колокольчик", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 4 },
    { name: "Язык дракона", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 5 },
    { name: "Яйцо коруса", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 10 },
    { name: "Яйцо оригмы", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 2 },
    { name: "Яйцо соснового дрозда", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 2 },
    { name: "Желе пепельного прыгуна", category: "Ингредиенты для алхимии", type: "misc", weight: 0.25, price: 20 },
    { name: "Желе нетча", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 20 },
    { name: "Перья фельсадской крачки", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 15 },
    { name: "Пепельная ползучая лоза", category: "Ингредиенты для алхимии", type: "misc", weight: 0.25, price: 20 },
    { name: "Императорский зонтичный мох", category: "Ингредиенты для алхимии", type: "misc", weight: 0.25, price: 1 },
    { name: "Стручок пепельной травы", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Пепел порождения", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 20 },
    { name: "Корень трамы", category: "Ингредиенты для алхимии", type: "misc", weight: 0.2, price: 1 },
    { name: "Кабаний клык", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 20 },
    { name: "Вредозобник", category: "Ингредиенты для алхимии", type: "misc", weight: 0.1, price: 1 },
    { name: "Древесина горелого сприггана", category: "Ингредиенты для алхимии", type: "misc", weight: 0.5, price: 20 },

    // --- 9. Сырые продукты ---
    { name: "Куриная грудка", category: "Сырые продукты", type: "food", weight: 0.2, price: 3 },
    { name: "Мясо устрицы", category: "Сырые продукты", type: "food", weight: 0.1, price: 1 },
    { name: "Собачатина", category: "Сырые продукты", type: "food", weight: 0.2, price: 3 },
    { name: "Мясо хоркера", category: "Сырые продукты", type: "food", weight: 1, price: 3 },
    { name: "Конина", category: "Сырые продукты", type: "food", weight: 2, price: 3 },
    { name: "Козий окорок", category: "Сырые продукты", type: "food", weight: 1, price: 3 },
    { name: "Хобот мамонта", category: "Сырые продукты", type: "food", weight: 3, price: 6 },
    { name: "Фазанья грудка", category: "Сырые продукты", type: "food", weight: 0.2, price: 3 },
    { name: "Сырая говядина", category: "Сырые продукты", type: "food", weight: 0.2, price: 4 },
    { name: "Сырая кроличья ножка", category: "Сырые продукты", type: "food", weight: 0.1, price: 2 },
    { name: "Лососина", category: "Сырые продукты", type: "food", weight: 0.1, price: 3 },
    { name: "Оленина", category: "Сырые продукты", type: "food", weight: 2, price: 4 },
    { name: "Капуста", category: "Сырые продукты", type: "food", weight: 0.25, price: 2 },
    { name: "Морковь", category: "Сырые продукты", type: "food", weight: 0.1, price: 1 },
    { name: "Тыква", category: "Сырые продукты", type: "food", weight: 0.2, price: 1 },
    { name: "Зелёное яблоко", category: "Сырые продукты", type: "food", weight: 0.1, price: 3 },
    { name: "Лук-порей", category: "Сырые продукты", type: "food", weight: 0.1, price: 1 },
    { name: "Картофель", category: "Сырые продукты", type: "food", weight: 0.1, price: 1 },
    { name: "Красное яблоко", category: "Сырые продукты", type: "food", weight: 0.1, price: 3 },
    { name: "Помидор", category: "Сырые продукты", type: "food", weight: 0.1, price: 4 },
    { name: "Мясо кабана", category: "Сырые продукты", type: "food", weight: 1, price: 2 },
    { name: "Мясо пепельного прыгуна", category: "Сырые продукты", type: "food", weight: 0.5, price: 2 },
    { name: "Нога пепельного прыгуна", category: "Сырые продукты", type: "food", weight: 1, price: 2 },
    { name: "Пепельный батат", category: "Сырые продукты", type: "food", weight: 0.1, price: 1 },

    // --- 10. Готовые продукты ---
    { name: "Яблочный пирог", category: "Готовые продукты", type: "food", weight: 0.5, price: 5 },
    { name: "Печёный картофель", category: "Готовые продукты", type: "food", weight: 0.1, price: 2 },
    { name: "Пирожное с заварным кремом", category: "Готовые продукты", type: "food", weight: 0.5, price: 4 },
    { name: "Хлеб", category: "Готовые продукты", type: "food", weight: 0.2, price: 2 },
    { name: "Капустный суп", category: "Готовые продукты", type: "food", weight: 0.5, price: 5 },
    { name: "Кусок эйдарского сыра", category: "Готовые продукты", type: "food", weight: 0.25, price: 5 },
    { name: "Круг эйдарского сыра", category: "Готовые продукты", type: "food", weight: 2, price: 13 },
    { name: "Кусок козьего сыра", category: "Готовые продукты", type: "food", weight: 0.25, price: 5 },
    { name: "Круг козьего сыра", category: "Готовые продукты", type: "food", weight: 2, price: 10 },
    { name: "Жареный лук-порей", category: "Готовые продукты", type: "food", weight: 0.1, price: 2 },
    { name: "Орехи в меду", category: "Готовые продукты", type: "food", weight: 0.1, price: 2 },
    { name: "Жареная рыба-убийца", category: "Готовые продукты", type: "food", weight: 0.1, price: 5 },
    { name: "Початый круг эйдарского сыра", category: "Готовые продукты", type: "food", weight: 2, price: 10 },
    { name: "Початый круг козьего сыра", category: "Готовые продукты", type: "food", weight: 2, price: 8 },
    { name: "Сладкий рулет", category: "Готовые продукты", type: "food", weight: 0.1, price: 2 },
    { name: "Вареное мясо кабана", category: "Готовые продукты", type: "food", weight: 1, price: 15 },

    // --- 11. Напитки ---
    { name: "Черновересковый мёд", category: "Напитки", type: "drink", weight: 0.2, price: 25 },
    { name: "Мёд Хоннинга", category: "Напитки", type: "drink", weight: 0.5, price: 20 },
    { name: "Вино «Алто»", category: "Напитки", type: "drink", weight: 0.5, price: 12 },
    { name: "Нордский мёд", category: "Напитки", type: "drink", weight: 0.5, price: 5 },
    { name: "Коловианский бренди", category: "Напитки", type: "drink", weight: 0.5, price: 100 },
    { name: "Огненное вино", category: "Напитки", type: "drink", weight: 0.5, price: 137 },
    { name: "Вино", category: "Напитки", type: "drink", weight: 0.5, price: 7 },
    { name: "Пряное вино", category: "Напитки", type: "drink", weight: 0.5, price: 7 },
    { name: "Строс М'Кайский ром", category: "Напитки", type: "drink", weight: 0.5, price: 12 },
    { name: "Черновересковый мёд отборный", category: "Напитки", type: "drink", weight: 0.5, price: 100 },
    { name: "Мед с можжевеловыми ягодами", category: "Напитки", type: "drink", weight: 0.5, price: 5 },
    { name: "Аргонианский эль", category: "Напитки", type: "drink", weight: 0.5, price: 5 },
    { name: "Вино Джесики", category: "Напитки", type: "drink", weight: 0.5, price: 12 },
    { name: "Зольный мед (алко)", category: "Напитки", type: "drink", weight: 0.5, price: 50 },
    { name: "Мацт", category: "Напитки", type: "drink", weight: 0.5, price: 5 },
    { name: "Суджамма", category: "Напитки", type: "drink", weight: 0.5, price: 10 },
    { name: "Угольное вино", category: "Напитки", type: "drink", weight: 0.5, price: 15 },
    { name: "Флин", category: "Напитки", type: "drink", weight: 0.5, price: 15 },
    { name: "Шейн", category: "Напитки", type: "drink", weight: 0.5, price: 10 },
    { name: "Красноводная скума", category: "Напитки", type: "drink", weight: 0.5, price: 75 },
    { name: "Зелье крови", category: "Напитки", type: "drink", weight: 0.5, price: 100 },
    { name: "Кувшин молока", category: "Напитки", type: "drink", weight: 1, price: 2 },

    // --- 12. Посохи (все 40) ---
    { name: "Посох мужества", category: "Посохи", type: "staff", weight: 8, price: 79, charges: 12, effect: "Цель не обращается в бегство 8 ходов +25 HP" },
    { name: "Посох вдохновения", category: "Посохи", type: "staff", weight: 8, price: 317, charges: 10, effect: "Цели не обращаются в бегство +35 HP" },
    { name: "Посох успокоения", category: "Посохи", type: "staff", weight: 8, price: 1153, charges: 6, effect: "Существа до 9 уровня не атакуют 7 ходов" },
    { name: "Посох страха", category: "Посохи", type: "staff", weight: 8, price: 2333, charges: 4, effect: "Существа до 9 уровня бегут 7 ходов" },
    { name: "Посох покорения", category: "Посохи", type: "staff", weight: 8, price: 1807, charges: 4, effect: "Существа до 18 уровня бегут 5 ходов" },
    { name: "Посох ярости", category: "Посохи", type: "staff", weight: 8, price: 803, charges: 10, effect: "Существа до 6 уровня атакуют любую цель 7 ходов" },
    { name: "Посох бешенства", category: "Посохи", type: "staff", weight: 8, price: 1149, charges: 6, effect: "Существа до 12 уровня атакуют любую цель 9 ходов" },
    { name: "Посох магического света", category: "Посохи", type: "staff", weight: 8, price: 239, charges: 12, effect: "Создаёт шар света на 5 ходов" },
    { name: "Великий посох отворота", category: "Посохи", type: "staff", weight: 8, price: 1520, charges: 4, effect: "Нежить до 13 уровня бегут 10 ходов" },
    { name: "Посох отворота", category: "Посохи", type: "staff", weight: 8, price: 1036, charges: 6, effect: "Нежить до 10 уровня бегут 7 ходов" },
    { name: "Малый посох отворота", category: "Посохи", type: "staff", weight: 8, price: 556, charges: 12, effect: "Нежить до 6 уровня бегут 7 ходов" },
    { name: "Великий посох отторжения", category: "Посохи", type: "staff", weight: 8, price: 1289, charges: 4, effect: "Нежить до 8 уровня бегут 7 ходов" },
    { name: "Посох отторжения", category: "Посохи", type: "staff", weight: 8, price: 675, charges: 6, effect: "Нежить до 6 уровня бегут 7 ходов" },
    { name: "Посох заживления", category: "Посохи", type: "staff", weight: 8, price: 613, charges: 6, effect: "Восстанавливает 50 HP заклинателя" },
    { name: "Посох исцеляющих рук", category: "Посохи", type: "staff", weight: 8, price: 198, charges: 12, effect: "Восстанавливает 20 HP цели за 1 ход" },
    { name: "Посох зомби", category: "Посохи", type: "staff", weight: 8, price: 449, charges: 10, effect: "Оживляет слабого мертвеца на 10 ходов" },
    { name: "Посох живых мертвецов", category: "Посохи", type: "staff", weight: 8, price: 949, charges: 10, effect: "Оживляет мертвеца 7 уровня на 10 ходов" },
    { name: "Посох неупокоенных", category: "Посохи", type: "staff", weight: 8, price: 824, charges: 6, effect: "Оживляет мертвеца 13 уровня на 2 хода" },
    { name: "Посох ужасных зомби", category: "Посохи", type: "staff", weight: 8, price: 1248, charges: 4, effect: "Оживляет мертвеца 17 уровня на 20 ходов" },
    { name: "Посох призыва питомца", category: "Посохи", type: "staff", weight: 8, price: 926, charges: 10, effect: "Призывает призрачного питомца на 10 ходов" },
    { name: "Посох огненного атронаха", category: "Посохи", type: "staff", weight: 8, price: 727, charges: 5, effect: "Призывает огненного атронаха на 15 ходов" },
    { name: "Посох ледяного атронаха", category: "Посохи", type: "staff", weight: 8, price: 1106, charges: 5, effect: "Призывает ледяного атронаха на 16 ходов" },
    { name: "Посох грозового атронаха", category: "Посохи", type: "staff", weight: 8, price: 1656, charges: 4, effect: "Призывает грозового атронаха на 20 ходов" },
    { name: "Посох изгнания", category: "Посохи", type: "staff", weight: 8, price: 926, charges: 6, effect: "Изгоняет даэдра до 10 уровня" },
    { name: "Посох высылки", category: "Посохи", type: "staff", weight: 8, price: 2092, charges: 4, effect: "Изгоняет даэдра до 15 уровня" },
    { name: "Посох даэдрического приказа", category: "Посохи", type: "staff", weight: 8, price: 2307, charges: 4, effect: "Контроль атронахов и даэдра до 15 уровня" },
    { name: "Посох захвата душ", category: "Посохи", type: "staff", weight: 8, price: 986, charges: 12, effect: "Заполняет камень душ при смерти цели в течение 7 ходов" },
    { name: "Посох пламени", category: "Посохи", type: "staff", weight: 8, price: 182, charges: 12, effect: "Струя пламени (16 урона + дополнительный)" },
    { name: "Посох огненных стрел", category: "Посохи", type: "staff", weight: 8, price: 456, charges: 10, effect: "Вспышка пламени (25 урона)" },
    { name: "Посох огненных шаров", category: "Посохи", type: "staff", weight: 8, price: 1309, charges: 6, effect: "Огненный взрыв (40 урона в радиусе 10 футов)" },
    { name: "Посох огненной стены", category: "Посохи", type: "staff", weight: 8, price: 1310, charges: 4, effect: "Стена огня (50 урона/ход, 12 ходов)" },
    { name: "Посох испепеления", category: "Посохи", type: "staff", weight: 8, price: 2750, charges: 4, effect: "Вспышка пламени (60 урона)" },
    { name: "Посох обморожения", category: "Посохи", type: "staff", weight: 8, price: 198, charges: 12, effect: "Струя холода (16 урона, замедление 25%)" },
    { name: "Посох ледяных шипов", category: "Посохи", type: "staff", weight: 8, price: 511, charges: 10, effect: "Ледяной шип (25 урона, замедление 25%)" },
    { name: "Посох ледяной бури", category: "Посохи", type: "staff", weight: 8, price: 1401, charges: 6, effect: "Ледяной вихрь (40 урона в радиусе 10 футов)" },
    { name: "Посох морозной стены", category: "Посохи", type: "staff", weight: 8, price: 1468, charges: 4, effect: "Стена мороза (8 урона/ход, 12 ходов)" },
    { name: "Посох ледяного копья", category: "Посохи", type: "staff", weight: 8, price: 2931, charges: 0, effect: "Ледяной шип (60 урона)" },
    { name: "Посох искр", category: "Посохи", type: "staff", weight: 8, price: 218, charges: 12, effect: "Электрический разряд (16 урона здоровью и магии)" },
    { name: "Посох молний", category: "Посохи", type: "staff", weight: 8, price: 538, charges: 10, effect: "Электрический разряд (25 урона, вдвое магии)" },
    { name: "Посох грома", category: "Посохи", type: "staff", weight: 8, price: 778, charges: 6, effect: "Молния (40 урона, перебрасывается)" },
    { name: "Посох цепных молний", category: "Посохи", type: "staff", weight: 8, price: 1494, charges: 4, effect: "Электрический разряд (60 урона, вдвое магии)" },
    { name: "Посох грозовой стены", category: "Посохи", type: "staff", weight: 8, price: 1531, charges: 4, effect: "Стена молний (8 урона/ход, 12 ходов)" },

    // --- 13. Маски жрецов ---
    { name: "Маска Азидала", category: "Маски жрецов", type: "armor", slot: "helmet", armor: 23, weight: 3, price: 1165, material: "Эбонитовый слиток", effect: "Сопротивление огню +50%, урон огнём +25%" },
    { name: "Закрисош", category: "Маски жрецов", type: "armor", slot: "helmet", armor: 23, weight: 4, price: 500, material: "Эбонитовый слиток", effect: "Сопротивление электричеству +50%, урон электричеством +25%" },
    { name: "Дукан", category: "Маски жрецов", type: "armor", slot: "helmet", armor: 23, weight: 4, price: 500, material: "Эбонитовый слиток", effect: "Сопротивление холоду +50%, урон холодом +25%" },

    // --- 14. Артефакты Азидала ---
    { name: "Азидалов шлем проницательности", category: "Артефакты Азидала", type: "armor", slot: "helmet", armor: 19, weight: 2, price: 1250, material: "Стальной слиток", effect: "Дальность колдовства и рун +15 футов, стоимость заклинаний +25%" },
    { name: "Азидалова броня возмездия", category: "Артефакты Азидала", type: "armor", slot: "chest", armor: 40, weight: 7, price: 2730, material: "Стальной слиток", effect: "1% шанс парализовать атакующего в ближнем бою" },
    { name: "Азидалово кольцо волшебства", category: "Артефакты Азидала", type: "jewelry", slot: "ring", weight: 0.333, price: 1435, effect: "Позволяет использовать «Поджиг» и «Заморозку» (стоимость 30 MP)" },
    { name: "Азидалово кольцо некромантии", category: "Артефакты Азидала", type: "jewelry", slot: "ring", weight: 0.333, price: 1110, effect: "Поднятое существо взрывается при получении урона, нанося 50 холода" },
    { name: "Азидаловы перчатки оберега", category: "Артефакты Азидала", type: "armor", slot: "gloves", armor: 14, weight: 3, price: 1750, material: "Стальной слиток", effect: "Обереги на 25% слабее, но поглощают 50% магии" },
    { name: "Азидаловы сапоги хождения по воде", category: "Артефакты Азидала", type: "armor", slot: "boots", armor: 14, weight: 4, price: 1125, material: "Стальной слиток", effect: "Хождение по воде, +10 к зачарованию при 4 реликвиях" },

    // --- 15. Броня Мораг Тонг ---
    { name: "Капюшон Мораг Тонг", category: "Броня Мораг Тонг", type: "armor", slot: "helmet", armor: 12, weight: 1, price: 2, material: "Кожа" },
    { name: "Наручи Мораг Тонг", category: "Броня Мораг Тонг", type: "armor", slot: "gloves", armor: 7, weight: 1, price: 25, material: "Кожа" },
    { name: "Броня Мораг Тонг", category: "Броня Мораг Тонг", type: "armor", slot: "chest", armor: 26, weight: 3, price: 150, material: "Кожа" },
    { name: "Сапоги Мораг Тонг", category: "Броня Мораг Тонг", type: "armor", slot: "boots", armor: 8, weight: 1, price: 35, material: "Кожа" },

    // --- 16. Уникальная броня (все сеты, уже готовые) ---
    { name: "Шлем Брурида", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 23, weight: 3, price: 1200, material: "Сталь", location: "Тревская застава", effect: "+25 МП, +5 навыка Разрушения" },
    { name: "Броня Брурида", category: "Уникальная броня", type: "armor", slot: "chest", armor: 32, weight: 3, price: 1500, material: "Сталь", location: "Тревская застава", effect: "+25 МП, +5 навыка Разрушения" },
    { name: "Перчатки Брурида", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 12, weight: 1, price: 800, material: "Сталь", location: "Тревская застава", effect: "+25 МП, +5 навыка Разрушения" },
    { name: "Сапоги Брурида", category: "Уникальная броня", type: "armor", slot: "boots", armor: 12, weight: 1, price: 800, material: "Сталь", location: "Тревская застава", effect: "+25 МП, +5% поглощения магии, +5 навыка Разрушения" },
    { name: "Ламеллярный шлем", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 19, weight: 2, price: 1100, material: "Ламеллярный", location: "Зуб Фалдара", effect: "+10 ХП, +10 брони, +5% сопр. магии" },
    { name: "Ламеллярная броня", category: "Уникальная броня", type: "armor", slot: "chest", armor: 31, weight: 3, price: 1400, material: "Ламеллярный", location: "Зуб Фалдара", effect: "+10 ХП, +25 брони, +5% сопр. магии" },
    { name: "Ламеллярные перчатки", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 14, weight: 1, price: 700, material: "Ламеллярный", location: "Зуб Фалдара", effect: "+10 ХП, +10 брони, +5% сопр. магии" },
    { name: "Ламеллярные сапоги", category: "Уникальная броня", type: "armor", slot: "boots", armor: 15, weight: 1, price: 700, material: "Ламеллярный", location: "Зуб Фалдара", effect: "+10 ХП, +25 брони, +5% сопр. магии" },
    { name: "Ламеллярный щит", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 25, weight: 4, price: 1200, material: "Ламеллярный", location: "Зуб Фалдара", effect: "+10 ХП, +25 брони, +5% сопр. магии" },
    { name: "Броня дезертира Стражи Рассвета", category: "Уникальная броня", type: "armor", slot: "chest", armor: 31, weight: 3, price: 1300, material: "Кожа (усиленная)", location: "Зуб Фалдара", effect: "Сопротивление холоду +20%, сопр. магии +10%" },
    { name: "Шлем Туманной заставы", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 16, weight: 2, price: 900, material: "Ламеллярный", location: "Туманная застава", effect: "+40 МП, +15% защиты от стрел, +10% сопр. электричеству" },
    { name: "Броня Туманной заставы", category: "Уникальная броня", type: "armor", slot: "chest", armor: 28, weight: 3, price: 1200, material: "Ламеллярный", location: "Туманная застава", effect: "+40 ХП, +10% сопр. огню" },
    { name: "Перчатки Туманной заставы", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 12, weight: 1, price: 700, material: "Ламеллярный", location: "Туманная застава", effect: "+15% защиты от стрел, +15% урона оружием" },
    { name: "Сапоги Туманной заставы", category: "Уникальная броня", type: "armor", slot: "boots", armor: 12, weight: 1, price: 700, material: "Ламеллярный", location: "Туманная застава", effect: "+10% сопр. холоду, +10 скорости" },
    { name: "Шлем Мясника", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 16, weight: 2, price: 1000, material: "Хитин", location: "Пещера Крегслейн", effect: "+25% сопр. холоду, видит врагов сквозь стены, замедляет время на 1 ход" },
    { name: "Броня Мясника", category: "Уникальная броня", type: "armor", slot: "chest", armor: 35, weight: 4, price: 1400, material: "Хитин", location: "Пещера Крегслейн", effect: "+40 ХП" },
    { name: "Перчатки Мясника", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 14, weight: 1, price: 800, material: "Хитин", location: "Пещера Крегслейн", effect: "+15% урона одноручным и двуручным" },
    { name: "Сапоги Мясника", category: "Уникальная броня", type: "armor", slot: "boots", armor: 13, weight: 1, price: 800, material: "Хитин", location: "Пещера Крегслейн", effect: "+5 скорости, +30 переносимого веса" },
    { name: "Шлем Линви", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 15, weight: 2, price: 900, material: "Уникальная кожа (х1.2)", location: "Пещера Говорящие Холмы", effect: "+15% урона стрелками, -15% стоимости Иллюзии" },
    { name: "Броня Линви", category: "Уникальная броня", type: "armor", slot: "chest", armor: 27, weight: 3, price: 1300, material: "Уникальная кожа (х1.2)", location: "Пещера Говорящие Холмы", effect: "+50 МП, -15% стоимости Иллюзии" },
    { name: "Перчатки Линви", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 11, weight: 1, price: 700, material: "Уникальная кожа (х1.2)", location: "Пещера Говорящие Холмы", effect: "+8% пробивания, -15% стоимости Иллюзии" },
    { name: "Сапоги Линви", category: "Уникальная броня", type: "armor", slot: "boots", armor: 11, weight: 1, price: 700, material: "Уникальная кожа (х1.2)", location: "Пещера Говорящие Холмы", effect: "+1 к скрытности" },
    { name: "Шлем Ингола", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 20, weight: 2, price: 1100, material: "Нордик", location: "Курган Ингола", effect: "+30 ХП, +15% сопр. холоду" },
    { name: "Броня Ингола", category: "Уникальная броня", type: "armor", slot: "chest", armor: 32, weight: 4, price: 1400, material: "Нордик", location: "Курган Ингола", effect: "+10% сопр. магии, +30% сопр. ядам" },
    { name: "Перчатки Ингола", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 14, weight: 1, price: 800, material: "Нордик", location: "Курган Ингола", effect: "+10% урона, +15% сопр. электричеству" },
    { name: "Сапоги Ингола", category: "Уникальная броня", type: "armor", slot: "boots", armor: 14, weight: 1, price: 800, material: "Нордик", location: "Курган Ингола", effect: "+15% сопр. огню" },
    { name: "Шлем Охотника Серебряной Руки", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 20, weight: 2, price: 1100, material: "Пластинчатое", location: "Кристальная пещера", effect: "+10% защиты от стрел, +50 брони" },
    { name: "Броня Охотника Серебряной Руки", category: "Уникальная броня", type: "armor", slot: "chest", armor: 38, weight: 4, price: 1500, material: "Пластинчатое", location: "Кристальная пещера", effect: "+50 ХП" },
    { name: "Перчатки Охотника Серебряной Руки", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 16, weight: 1, price: 900, material: "Пластинчатое", location: "Кристальная пещера", effect: "+15% урона, +10% сопр. магии" },
    { name: "Сапоги Охотника Серебряной Руки", category: "Уникальная броня", type: "armor", slot: "boots", armor: 16, weight: 1, price: 900, material: "Пластинчатое", location: "Кристальная пещера", effect: "+10 скорости" },
    { name: "Шлем Разорителя (Открытый)", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 22, weight: 2, price: 1300, material: "Нордик", location: "Ветреный Пик", effect: "+5% сопр. магии, +20% сопр. холоду, при сете: +120 брони" },
    { name: "Шлем Разорителя (Закрытый)", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 22, weight: 2, price: 1300, material: "Нордик", location: "Курган Железный", effect: "+5% сопр. магии, +20% сопр. холоду, при сете: -10% физ. урона" },
    { name: "Броня Разорителя", category: "Уникальная броня", type: "armor", slot: "chest", armor: 36, weight: 4, price: 1600, material: "Нордик", location: "Ведьмино Гнездо", effect: "+10% сопр. магии, +55 ХП, +30 переносимого веса" },
    { name: "Перчатки Разорителя", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 16, weight: 1, price: 1000, material: "Нордик", location: "Первое древненордское подземелье", effect: "+20% сопр. электричеству, +20% урона" },
    { name: "Сапоги Разорителя", category: "Уникальная броня", type: "armor", slot: "boots", armor: 16, weight: 1, price: 1000, material: "Нордик", location: "Нчуанд-Зел", effect: "+20% сопр. огню, +5 скорости" },
    { name: "Шлем Пенитус Окулатус", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 18, weight: 2, price: 1000, material: "Имперская броня (х1.5)", location: "При убийстве начальника Пенитус", effect: "+10% физ. урона" },
    { name: "Броня Пенитус Окулатус", category: "Уникальная броня", type: "armor", slot: "chest", armor: 30, weight: 3, price: 1300, material: "Имперская броня (х1.5)", location: "При убийстве начальника Пенитус", effect: "25 ХП, 10% сопр. магии" },
    { name: "Наручи Пенитус Окулатус", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 14, weight: 1, price: 800, material: "Имперская броня (х1.5)", location: "При убийстве начальника Пенитус", effect: "50 пробития, 10% сопр. стрелам" },
    { name: "Сапоги Пенитус Окулатус", category: "Уникальная броня", type: "armor", slot: "boots", armor: 14, weight: 1, price: 800, material: "Имперская броня (х1.5)", location: "При убийстве начальника Пенитус", effect: "+10% сопр. магии" },
    { name: "Шлем Джари-Ра", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 14, weight: 2, price: 800, material: "Кожаная", location: "Грот Сломанное Весло", effect: "+10% урона стрелками, +10% сопр. стрелам" },
    { name: "Броня Джари-Ра", category: "Уникальная броня", type: "armor", slot: "chest", armor: 24, weight: 3, price: 1200, material: "Кожаная", location: "Грот Сломанное Весло", effect: "25 ХП, +10% урона стрелками" },
    { name: "Перчатки Джари-Ра", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 10, weight: 1, price: 600, material: "Кожаная", location: "Грот Сломанное Весло", effect: "50 пробития стрелками" },
    { name: "Сапоги Джари-Ра", category: "Уникальная броня", type: "armor", slot: "boots", armor: 10, weight: 1, price: 600, material: "Кожаная", location: "Грот Сломанное Весло", effect: "+15 скорости" },
    { name: "Шлем древнего вампира", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 24, weight: 2, price: 1400, material: "Эбонит (х1.1)", location: "Кровавый Трон", effect: "+25% сопр. электричеству, +10% физ. урона" },
    { name: "Броня древнего вампира", category: "Уникальная броня", type: "armor", slot: "chest", armor: 40, weight: 4, price: 1700, material: "Эбонит (х1.1)", location: "Кровавый Трон", effect: "+25% сопр. огню, +15% сопр. магии" },
    { name: "Перчатки древнего вампира", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 18, weight: 1, price: 1000, material: "Эбонит (х1.1)", location: "Кровавый Трон", effect: "+25% сопр. огню, 50 пробития" },
    { name: "Сапоги древнего вампира", category: "Уникальная броня", type: "armor", slot: "boots", armor: 18, weight: 1, price: 1000, material: "Эбонит (х1.1)", location: "Кровавый Трон", effect: "+10 скорости, 10% поглощения магии" },
    { name: "Стеклянный шлем", category: "Уникальная броня", type: "armor", slot: "helmet", armor: 17, weight: 2, price: 1100, material: "Малахит", location: "Ветровая Дуга", effect: "+10% защиты от стихий, +30 брони" },
    { name: "Стеклянная броня", category: "Уникальная броня", type: "armor", slot: "chest", armor: 32, weight: 3, price: 1500, material: "Малахит", location: "Северная сторожевая крепость", effect: "+10% поглощения магии, +70 ХП/МП" },
    { name: "Стеклянные перчатки", category: "Уникальная броня", type: "armor", slot: "gloves", armor: 13, weight: 1, price: 800, material: "Малахит", location: "Близ Талморского посольства", effect: "+20% урона, +1 к кубам атаки" },
    { name: "Стеклянные сапоги", category: "Уникальная броня", type: "armor", slot: "boots", armor: 13, weight: 1, price: 800, material: "Малахит", location: "Кагрензел", effect: "+10% поглощения магии, +5 скорости" },

    // --- 17. Уникальные щиты ---
    { name: "Стойкость", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 30, weight: 8, price: 1200, material: "Нордик", location: "Туманная застава", effect: "+30 ХП, +100 брони во время блока" },
    { name: "Тарч Кровожадности", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 26, weight: 4, price: 1000, material: "Сталь", location: "Альфтанд", effect: "+25 урона кровотечением при силовой атаке щитом" },
    { name: "Бастион", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 28, weight: 6, price: 1100, material: "Ламеллярный", location: "Привал Хамвира", effect: "+10% урона оружием" },
    { name: "Прочный железный щит", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 26, weight: 7, price: 900, material: "Железо", location: "Лагерь Тихих Лун", effect: "+20 ХП, 10% отражения урона" },
    { name: "Этериевый щит", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 30, weight: 13, price: 1400, material: "Двемерский", location: "Кузница этерия", effect: "+40 ХП, +10% сопр. стихиям, +10% поглощения магии" },
    { name: "Равновесие", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 26, weight: 4, price: 1000, material: "Сталь", location: "Приют Редорана", effect: "+50 брони, +10% сопр. стихиям" },
    { name: "Щит налетчика", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 27, weight: 4, price: 800, material: "Сталь", location: "Убийство налетчика", effect: "+25 урона кровотечением при силовой атаке" },
    { name: "Гордыня", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 28, weight: 4, price: 1300, material: "Эбонит", location: "Пещера Каменный Ручей", effect: "+55 ХП, 25% сопр. огню, 60 урона при ударе" },
    { name: "Печаль Исграмора", category: "Уникальные щиты", type: "armor", slot: "shield", armor: 32, weight: 4, price: 1500, material: "Нордик", location: "Курган Ингола", effect: "25% сопр. электричеству, разрушает броню цели на 100 на 10 ходов" },

    // --- 18. Даэдрические артефакты ---
    { name: "Кольцо Кхаджита", category: "Даэдрические артефакты", type: "jewelry", slot: "ring", weight: 0.25, price: 2837, effect: "+2 к кубам на Скрытность, «Скрытый шаг» 1/день", quest: "Квест «Мертвый узел»" },
    { name: "Зеркало Квандри", category: "Даэдрические артефакты", type: "armor", slot: "shield", weight: 2, price: 4088, effect: "При блоке атакующий делает спасбросок Мудрости (СЛ15) или «Ужас Вермины»", quest: "Кошмар Неласара" },
    { name: "Рубиновый Тронный Кинжал", category: "Даэдрические артефакты", type: "weapon", slot: "melee", weight: 2, price: 3080, dmg: 8, effect: "Атака по союзнику/неожидающей цели → урон ×4.5, убийство +25 маны", quest: "Интриги легата в Солитьюде" },
    { name: "Кольцо Эпидемии", category: "Даэдрические артефакты", type: "jewelry", slot: "ring", weight: 0.25, price: 2624, effect: "Иммунитет к болезням, за каждую болезнь +5 урона и +1 куб, раз в день «Чумное облако»", quest: "Культ Периайта" },
    { name: "Кубок Бесконечного Хмеля", category: "Даэдрические артефакты", type: "misc", slot: "misc", weight: 1, price: 2418, effect: "Глоток – снимает замедление, +4 Силы на 3 хода, -2 куба на стрельбу/магию", quest: "В «Гарцующей кобыле»" },
    { name: "Топор Жатвы", category: "Даэдрические артефакты", type: "weapon", slot: "melee", weight: 14, price: 3000, dmg: 25, effect: "Крадёт 15 ХП и 15 МП, убитый восстаёт зомби", quest: "Раргал Хозяин Трэллов" },
    { name: "Звезда Судьбы", category: "Даэдрические артефакты", type: "jewelry", slot: "misc", weight: 2, price: 2571, effect: "Раз в день перебросить куб, при убийстве врага оружие перезаряжается", quest: "Защита святилища Азуры" },
    { name: "Оковы Отверженных", category: "Даэдрические артефакты", type: "armor", slot: "gloves", armor: 15, weight: 6, price: 2982, effect: "Силовая атака двуручным оружием нивелирует штраф, враг получает -2 куба на 3 хода", quest: "Очистка крепости Лоргашбур (Малакат)" },
    { name: "Кольцо Очищающего Света", category: "Даэдрические артефакты", type: "jewelry", slot: "ring", weight: 0.25, price: 2060, effect: "Двойной урон по нежити, раз в день «Вспышка Меридии»", quest: "Очистка Саартала (Меридия)" },
    { name: "Огненный Спектр Разрушения", category: "Даэдрические артефакты", type: "weapon", slot: "ranged", weight: 6, price: 2862, dmg: 0, effect: "40 урона огнём по площади, горение 1d6 за ход, 2% шанс мгновенной смерти", quest: "Святилище Мерунеса Дагона" },
    { name: "Чернильное Око Провидца", category: "Даэдрические артефакты", type: "jewelry", slot: "circlet", weight: 2, price: 2511, effect: "+3 Интеллекта, раз в неделю изучить заклинание Адепта, раз в день видеть ХП/МП/уязвимости", quest: "Арнел Гейн / Энтир" },
    { name: "Шкура Спасителя", category: "Даэдрические артефакты", type: "armor", slot: "chest", armor: 20, weight: 4, price: 2394, effect: "20% резист магии, 30% резист ядам, вервольфам: +6 часов трансформации", quest: "Великий Гон в Вечнозелёной роще" },
    { name: "Кольцо Намиры", category: "Даэдрические артефакты", type: "jewelry", slot: "ring", weight: 0.25, price: 2529, effect: "+50 ХП, после боя съесть труп → +50 ХП, +20 веса, +10% физ. урона на 24 часа", quest: "Защита святилища Намиры" },
    { name: "Чаша Благословения", category: "Даэдрические артефакты", type: "misc", slot: "misc", weight: 1, price: 2245, effect: "Навсегда увеличивает самую большую характеристику на 5, уменьшает самую маленькую на 5", quest: "Пёс Барбас и Клавикус Вайл" },
    { name: "Ваббаджек", category: "Даэдрические артефакты", type: "weapon", slot: "ranged", weight: 5, price: 2433, dmg: 0, effect: "10 зарядов. Бросок 1d100: 1-25 → кролик/злокрыс; 26-50 → 50 урона случайной стихией; 51-75 → исцеление; 76-95 → центурион (враг); 96-100 → мгновенная смерть", quest: "Крыло Пелагия III" },
    { name: "Серый Капюшон Ноктюрнал", category: "Даэдрические артефакты", type: "armor", slot: "helmet", weight: 2, price: 2229, armor: 0, effect: "Стирает личность из памяти NPC, штрафы падают до 0, +3 куба на Скрытность, проход сквозь врагов", quest: "Лощина Сломанный Шлем" },
    { name: "Камень Ситиса", category: "Даэдрические артефакты", type: "misc", slot: "misc", weight: 1, price: 2969, effect: "Одноразовый – при гибели команды воскрешает на месте с 50% ХП/МП", quest: "Скрытый квест (1-2 жизни)" }
];

// Делаем глобально доступным для мастера
window.allItems = allItems;